### ISSUE TITLE
How do I add an exception? if Appname is not found

### ISSUE THREAD

**Issue by Sahil481** [athrvvvv/AppOpener#11]
The app opener when using the open() function does not throw an error and rather prints to terminal. This makes it hard to do certain things such as speak something using speech recognition library when like the app is not found

**Comment by athrvvvv** [comment]
You could try like

``` py
from AppOpener import open

try:
    open("XYZ", output=True)
except Exception as e:
    print(str(e))  # prints "XYZ was not found"
    print("HELLO")
```

**Comment by Sahil481** [comment]
That will give me a list of applications but What I propose is that when a app is not found from this code

```Python
def open_things(self, output=True, match_closest=False):
    with open ((os.path.join(main_path,"data.json")),"r") as f:
        data1 = json.load(f)
        keys = data1.keys()
        try:
            dir01 = data1[self]
            os.system("explorer shell:appsFolder\\"+dir01)
            # print(("explorer shell:appsFolder\\"+dir01))
            if output:
                print("OPENING "+self.upper())
        except:
            result = difflib.get_close_matches(self,keys, n=1, cutoff=0.6)
            app_name = ' '.join(result).strip()
            if result:
                if output:
                    print("Closest match to "+self.upper()+" : "+str(result))
                if match_closest:
                    dir01 = data1[app_name]
                    os.system("explorer shell:appsFolder\\"+dir01)
                    # print("explorer shell:appsFolder\\"+app_name)
                    if output:
                        print("OPENING "+app_name.upper())
            else:
                if output:
                    ''' Instead of printing this line it should throw an error '''
                    print(f"{self.upper()} NOT FOUND... TYPE (LS) for list of applications.")
            pass
```

Look at the code in the if output block. It should throw an error so that we can handle it as we like.

**Comment by athrvvvv** [comment]
Yup!! If appname is not registered, it just passes it. We'll fix this on next version

**Comment by athrvvvv** [comment]
Actually we could do something like, `open("XYZ", throw_error=True)` in the next version

**Comment by Sahil481** [comment]
Yeah, I agree with the throw_error solution since it gives a choice. Do you mind if I work on this change? I would be glad to help

**Comment by Sahil481** [comment]
Yeah, I agree with the throw_error solution since it gives a choice. Do you mind if I work on this change? I would be glad to help

**Comment by athrvvvv** [comment]
Hello I think we can do the same thing with `open("XYZ", output=True)` which prints that app is registered something like this... 
The pr you made seems useless 😑

Actually, I forgotten the `output` attribute exists 😂

but yeah, thanks for the pr 🫶

**Comment by Sahil481** [comment]
No problem dude 🔥Keep coding

**Comment by Sahil481** [comment]
Actually the output=True, just prints when the app is not found or when a app is not running. But if it threw an error then I can do something like:
```python
try:
    open("XYZ", throw_error=True)
except:
    # Now i can do whatever I want here like
    # using the pyttsx3 library I can make it speak something 
    engine = pyttsx3.init()
    engine.say("The App you want to open was not found")
    engine.runAndWait()
```
It just expands the usability of the module. Previously we couldn't do that because it was just a print statement. 
I know it sounds weird becuase I want it to throw an error 😅 but in some cases it's better like the above example that's why I did the PR.

**Comment by athrvvvv** [comment]
You seem beginner in python, here how you may do this **without throw_error** attribute:

``` py
from AppOpener import open

try:
    open("XYZ", output=True)
except Exception as e:
    print(str(e))  # prints "XYZ was not found"
    print("DO NOW WHATEVER YOU WANNA DO")
```

I would pull back the changes :) Btw, thanks for the pull request ✨🤗

**Comment by Sahil481** [comment]
Actually your code dosen't even throw an exception error.
Try this code first:
```python
from AppOpener import *

try:
    open("XYZ", output=True)
except Exception as e:
    pass
```
Even if you don't print the exception it'll still print his line "XYZ" was not found. Explained later why

then try this:
```python
from AppOpener import *

try:
    open("XYZ", output=True)
except Exception as e:
    print("DID IT THROW AN ERROR?")
```

Then check the output. In the output you won't see this "DID IT THROW AN ERROR?" 
You can put anything in the except block it won't be executed even if the app is not found. Yes this "XYZ was not found" will be printed because this is being done through your code in this line. Even if you do not print the exception it will still print it, because there is no exception and the exception is not even a thing.

```python
if output:
     ''' Instead of printing this line it should throw an error '''
     print(f"{self.upper()} NOT FOUND... TYPE (LS) for list of applications.")
```

Because printing to the console is not the same as raising an error like in my pr. Please do try this in your version of the code and then tell me if it worked because it shouldn't work and I'm pretty sure it's not working for anyone. Try and put anything in the except block it won't get executed in your version of the code, and then try the same in my version of the code. 
And I am actually not a beginner in python I'm pretty advanced building APIs and almost a data analyst. Please do do these run's and then tell me what you see.

**Comment by athrvvvv** [comment]
```py
import io
from contextlib import redirect_stdout
from AppOpener import open

output = io.StringIO()
with redirect_stdout(output):
    open("XYZ", output=True)

if " NOT FOUND" in output.getvalue():
    print("DO WHATEVER YOU WANNA DO")
```

but thats the long route... I will keep the `throw_error` attribute 💁‍♂️⚡🤝

**Comment by Sahil481** [comment]
Yeah, that is a solution but it's not really developer friendly and it's pretty expected by developers nowdays that the code will throw an error. That is why throw_error attribute is necessary. Thanks for making this module btw love it 💖
