### ISSUE TITLE
Closing File Explorer Closes Desktop on Windows

### ISSUE THREAD

**Issue by taw5578** [athrvvvv/AppOpener#15]
Using this library to close the 'File Explorer' app causes the Windows desktop to disappear.

**Comment by athrvvvv** [comment]
Yes, but you can also start it like:

```py
from AppOpener import open
open("explorer", match_closest=True)
```

**Comment by taw5578** [comment]
Yes that is true, but that still does not resolve the issue. If at any point the close() method is used on file explorer, the Windows desktop disappears. The ability to close file explorer should either be removed or fixed. Opening it right after closing it does not resolve the issue.

**Comment by athrvvvv** [comment]
Okay, next version fixes this!! 🥰

**Comment by athrvvvv** [comment]
**AppOpener v1.7** just released!! ✌️

Install AppOpener v1.7:
``` cmd
pip install AppOpener==1.7
```

## Close `File Explorer` **without closing the windows**

``` python
from AppOpener import close
close("file explorer")
```

Lots of love,
athrv.
