### ISSUE TITLE
site-packages\\AppOpener\\Data\\reference.txt

### ISSUE THREAD

**Issue by ITSME1516** [athrvvvv/AppOpener#16]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\aadhi\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\AppOpener\\Data\\reference.txt'

Iam unable to import AppOpener

**Comment by athrvvvv** [comment]
Ok, We will solve it. Telegram me https://telegram.me/athrvvvv

**Comment by ITSME1516** [comment]
can you please clarify here?

**Comment by athrvvvv** [comment]
@ITSME1516 Actually dude, I have to **experiment some updates to solve this issue** 😊

If you are uncomfortable to connect on Telegram. **Here's my email**: codingbruh.ac@gmail.com 👍

**Comment by ITSME1516** [comment]
i connected to telegram . you didnt dave reply ...

**Comment by athrvvvv** [comment]
It's the user side issue.
