### ISSUE TITLE
About AppNotFound except 

### ISSUE THREAD

**Issue by Dannybobo** [athrvvvv/AppOpener#17]
Hi, here is my code
try:
     open("netflix", throw_error=True)
except AppNotFound as e:
      wb.open_new_tab('https://www.netflix.com/tw/')

I think, when netflix app is not open, it will raise some exception like AppNotFound, but it didn't work,
if I write the wrong code to use this function, please show me the right way, thanks.

**Comment by athrvvvv** [comment]
Actually there is no thing as **AppNotFound** in AppOpener till now.

Try this:
``` py
from AppOpener import open

try:
    open("netflix", throw_error=True)
except:
    wb.open_new_tab('https://www.netflix.com/tw/')
```
