### ISSUE TITLE
Microsoft store is not closing

### ISSUE THREAD

**Issue by Harsh011000** [athrvvvv/AppOpener#21]
when i open microsoft store using open() method it works but when i try close() method to close microsoft store it show microsoft is not running even if it is running everytime.
it has the same problem with winrar,microsoft to do also

**Comment by athrvvvv** [comment]
If you add exception manually like this:

``` python
from AppOpener import close
import pygetwindow as gw

def close_ms_store():
    try:
        ms_store_windows = gw.getWindowsWithTitle("Microsoft Store")
        if ms_store_windows:
            for window in ms_store_windows:
                if "Microsoft Store" in window.title:
                    window.close()
            print("Microsoft Store closed successfully.")
        else:
            print("Microsoft Store window not found.")
    except Exception as e:
        print(f"Error: {e}")
        
try:
    close("Microsoft Store", throw_error=True)
except:
    close_ms_store()
```

Note: `pip install PyGetWindow` 

You may make pull request integrating this into AppOpener. If not, don't worry next version will fix this 👍(it will take time, until use above method)
