### ISSUE TITLE
CANNOT OPEN APPS INSTALLED IN CHINESE

### ISSUE THREAD

**Issue by francohandel** [athrvvvv/AppOpener#5]
Apps with English names can open correctly, but when I try to open apps with Chinese names, nothing is done.
I have also tried renaming the apps but to no avail and the function run(LS) does not list the app either.

**Comment by athrvvvv** [comment]
@francohandel Hello, there... 
Tell me following things to counter this issue
1) What version of windows you're using
2) Some examples of chinese apps

After renaming the app names, have you tried (update) function or (default) function, if not try and tell me what appears. It will be nice if you share review with screenshots.
